### PR TITLE
Added contributions of each student

### PR DESCRIPTION
**Pull request by VamsiSangam**
This PR is for the issue #110 

[Live Demo URL](https://vamsisangam.github.io/opencodecollab/)

### Short description of changes made

Uses [GitHub API](https://api.github.com/repos/fossiiita/opencodecollab/contributors) to fetch details of contributors.

### CODE REVIEW

**Comment by gauthamzz** [comment]
its showing 0 for some people

**Comment by VamsiSangam** [comment]
Ok, I was using [contributors](https://api.github.com/repos/fossiiita/opencodecollab/contributors) for retrieving info, I didn't think the [commits](https://api.github.com/repos/fossiiita/opencodecollab/commits) request would work as it wasn't showing all the commits. But I found a way to [tweak it](https://api.github.com/repos/fossiiita/opencodecollab/commits?per_page=1000) to show more commits. It should be more accurate. Will modify my code. Closing this PR now.

**Comment by gauthamzz** [comment]
show for everyone not just students.
make a separate section for it.
we want to keep this section as the total contributions of the event

**Comment by VamsiSangam** [comment]
Everyone in the sense? Mentors too?

**Comment by VamsiSangam** [comment]
Wouldn't it be better if we had a leaderboard displaying the points and contributions of all the participants? It showcases the contributions to the event too and the rankings will usher more enthusiasm in participants

**Comment by gauthamzz** [comment]
yeah we are going to have a contributions page , three pages 
1. ranking :  ranked based on scores 
 displays number of contributions each person made , mentor and particpant

and other two as dicussed . i am going to make an issue . was waiting for #159 this to be done

**Pull request closed without merging**
