### PR TITLE
#101 Add fb like button to the site

### PR DESCRIPTION
**Pull request by RavicharanN**
fb like button links to the open code fb page

### CODE REVIEW

**Comment by gauthamzz** [comment]
link or screenshot ?

**Comment by RavicharanN** [comment]
screenshot of the modified page?

**Comment by RavicharanN** [comment]
screen shot 2017-01-24 at 12 12 15 am

will this do?

**Comment by gauthamzz** [comment]
Remove facebook from nav bar . And nave bar is getting elongated, looks weird .

**Comment by RavicharanN** [comment]
is it ok when the like and share buttons are below tha nav bar?

**Comment by gauthamzz** [comment]
@RavicharanN keep it header but in the same level as others
 but please change the color so that will match the website's navbar

**Comment by VamsiSangam** [comment]
May I pick up this issue?

**Comment by gauthamzz** [comment]
@VamsiSangam yeah sure go ahead

**Pull request closed without merging**
