### PR TITLE
Added trailer.Issue no.(#93)

### PR DESCRIPTION
**Pull request by Anupam-dagar**

### CODE REVIEW

**Comment by gauthamzz** [comment]
its a bit too large

**Comment by Anupam-dagar** [comment]
Ok, I will fix it by tomorrow.

**Comment by gauthamzz** [comment]
You can look into #97 for ideas , vamsi already solved it . but since you started working on it first

**Comment by Anupam-dagar** [comment]
Ok sir, I will take help from there.

**Pull request closed without merging**
