### PR TITLE
Added trailer.Issue no.(#93)

### PR DESCRIPTION
**Pull request by Anupam-dagar**
live link:
https://anupam-dagar.github.io/opencodecollab/

### CODE REVIEW

**Comment by gauthamzz** [comment]
screenshot_2017-01-23-08-44-30-016
In mobile view . Take care of this

**Comment by gauthamzz** [comment]
`https://anupam-dagar.github.io/opencodecollab/#myModal` is the url . it should be `https://anupam-dagar.github.io/opencodecollab/#Trailer`

**Comment by Anupam-dagar** [comment]
I was going to commit changes,will change this too.
Okay I will squash all the pull requests.

**Comment by Anupam-dagar** [comment]
screenshot from 2017-01-23 15-21-36
Problem in squashing commits.Help needed.

**Pull request merged**
