### PR TITLE
Close Chat Box

### PR DESCRIPTION
**Pull request by agbilotia1998**
#191 Added close button

### CODE REVIEW

**Comment by gauthamzz** [comment]
the button is supposed to close the chat only , this doesnt work

**Comment by agbilotia1998** [comment]
close
Sir,I thought on clicking the cross button appearing in chat box should close the box....

It is still unclear,please reexplain

**Comment by gauthamzz** [comment]
it should close the chat and resume with the website nah . Your thing just redirects me to somewhere else

**Comment by agbilotia1998** [comment]
Thankyou Sir ,
 Actually the two divisions were crossing..

**Comment by gauthamzz** [comment]
LGTM

**Comment by agbilotia1998** [comment]
@gauthamzz  Now its working, you can  test previous commit

**Pull request merged**
