### PR TITLE
Added scores.yml

### PR DESCRIPTION
**Pull request by VamsiSangam**
Adding empty ```scores.yml```. This is for the rankings as discussed with @gauthamzz  in #64 . After this merge, I will create a new issue asking students to add details of their contributions into this file.

### CODE REVIEW

**Comment by gauthamzz** [comment]
can you add all students name as well in the file

**Comment by VamsiSangam** [comment]
Ok sure. Just the names, or any other details as well?

**Comment by VamsiSangam** [comment]
I was planning to have each student's name, image, github username attributes along with the mandatory total and contributions fields.

**Comment by VamsiSangam** [comment]
I was thinking each student would have details listed out in this fashion -

```
- name: Vamsi Sangam
  image: vamsisangam.jpg
  github: VamsiSangam
  contributions:
    - name: Added profile to students
      link: https://github.com/fossiiita/opencodecollab/pull/7
      score: 30
    - name: Enable gh-pages on your fork
      link: https://github.com/fossiiita/opencodecollab/issues/15#issuecomment-273281903
      score: 30
  total: 60
```
```image``` and ```github``` fields would help while displaying candidate's pic on the leaderboard.

**Comment by gauthamzz** [comment]
yeah this looks better , i fear the file will get too large

**Comment by VamsiSangam** [comment]
I don't think it can be helped if you want to store all the contributions

**Comment by Anupam-dagar** [comment]
So after every successfull pull reuqest, we will have to add the data in this file. Right?

**Comment by VamsiSangam** [comment]
Yes that's the plan

**Comment by gauthamzz** [comment]
i think its better to have a contributions.yml file with student name , but this work too 

@adeora7 @shubham-padia  what do you guys say ?

**Comment by adeora7** [comment]
could you please elaborate. You mean one file for each student ? @gauthamzz

**Comment by shubham-padia** [comment]
Instead we can have the students list out the breakdown of points and link of all pull requests in a separate gist file and give a link to that file. Participants will have to change the total with each pull request and update the gist accordingly

**Comment by gauthamzz** [comment]
i mean like make a file points.yml 
and in it 
- student name
 contributions:
    - name: Added profile to students
      link: https://github.com/fossiiita/opencodecollab/pull/7
      score: 30
    - name: Enable gh-pages on your fork
      link: https://github.com/fossiiita/opencodecollab/issues/15#issuecomment-273281903
      score: 30
  total: 60

will be there or should we jsut add it in students.yml

**Comment by gauthamzz** [comment]
i like padia's idea

**Comment by VamsiSangam** [comment]
@shubham-padia 's idea sounds nice. But then all the gists need to have a fixed format, JSON perhaps. But still, if it is a gist, we would lose control over the list of contributions. The participant may/may not update them, or the participant may follow different format.

**Comment by VamsiSangam** [comment]
And a gist is more of an individual thing, it seems like we separating an event related entity from the event itself.

**Comment by gauthamzz** [comment]
we need to figure out a solution fast :/

**Comment by VamsiSangam** [comment]
If we have contributions in the ```.yml```, later on while implementing the leaderboard, we can easily list out a candidate's total and contributions using simple loops... If we have it in a separate gist, we would need to load it via AJAX. And because we would have to load it asynchronously I said we would need the gists to be in JSON. And we can't monitor each candidate's gists. If one candidate messes up their gist, their contributions may not get displayed, and we'd probably have to PM them. I'm just saying having contributions in ```.yml``` may make it big but its neat.

**Comment by gauthamzz** [comment]
you are right @VamsiSangam but if we write everything in students.yml small changes may cause it to break. thats why thought of having a seperate yml file. a simple loop will also work in this case.

**Comment by gauthamzz** [comment]
i think we shouldnt have duplicate data. i think github username will be sufficient and we can pick up others from the students.yml file

**Comment by VamsiSangam** [comment]
Ok then this is what would go into scores.yml -

```
- github: VamsiSangam
  contributions:
    - name: Added profile to students
      link: https://github.com/fossiiita/opencodecollab/pull/7
      score: 30
    - name: Enable gh-pages on your fork
      link: https://github.com/fossiiita/opencodecollab/issues/15#issuecomment-273281903
      score: 30
  total: 60
```

Is this what you meant?

**Comment by gauthamzz** [comment]
github id will be like a primary key , yeah exactly

**Comment by VamsiSangam** [comment]
Ok we will wait for what @shubham-padia and @adeora7 have to say about this. Meanwhile, let's say I have my primary key value, say ```VamsiSangam```, and to search its data in students.yml, should I just loop over the file or is there any construct which helps me do that?

**Comment by gauthamzz** [comment]
https://jekyllrb.com/docs/datafiles/

**Comment by shubham-padia** [comment]
https://github.com/fossiiita/opencodecollab/pull/125#issuecomment-275234490 Sounds good. Implement it for now, if we face any issues with this approach we can always change it :stuck_out_tongue:

**Comment by VamsiSangam** [comment]
Please review the format. If everything's okay, after the merge I will create an issue asking others to fill in their contributions.

**Pull request merged**
