### PR TITLE
Added trailer

### PR DESCRIPTION
**Pull request by VamsiSangam**
For #93 . [Demo URL](https://vamsisangam.github.io/opencodecollab/). Modal based implementation. Trigger for modal is on the navbar.

### CODE REVIEW

**Comment by gauthamzz** [comment]
but @Anupam-dagar was working on this already on #96 , please work on another issue . we dont want duplicated effort . There are more issues you can work on

**Comment by VamsiSangam** [comment]
I actually wrote the code well before. Was waiting for my previous PR. No worries. I'll work on the stars issue 😄

**Comment by gauthamzz** [comment]
from next time , comment on the issue you are working on . i will assign to you

**Comment by VamsiSangam** [comment]
Sure!

**Pull request closed without merging**
