### PR TITLE
Add Bhanu to students list

### PR DESCRIPTION
**Pull request by bhanu1911**

### CODE REVIEW

**Comment by gauthamzz** [comment]
@bhanu1911 i dont think the image is 240px240 p can you fix that

**Comment by bhanu1911** [comment]
No sir, I cannot, don't have the software to

**Comment by gauthamzz** [comment]
You can do it online

**Comment by bhanu1911** [comment]
Sir I edited the photo to the given size

**Comment by gauthamzz** [comment]
the image images/students/15590024_1244234475636091_4121290117102147387_n.jpg is not needed remove it ,please

**Comment by bhanu1911** [comment]
Done sir

**Comment by gauthamzz** [comment]
LGTM merged :+1:

**Pull request merged**
