### PR TITLE
Add Akshat Jain in students section

### PR DESCRIPTION
**Pull request by dabbler011**

### CODE REVIEW

**Comment by gauthamzz** [comment]
LGTM :+1: please do social media post and share the link

**Comment by dabbler011** [comment]
https://www.facebook.com/akshatj011?fref=nf

**Comment by gauthamzz** [comment]
no you have to post on social media that you are participating in opencode , and show link for that :confused: with hashtags #geekhaveniiita #opencode #iiiita

**Comment by dabbler011** [comment]
Udated my post:
https://m.facebook.com/story.php?story_fbid=1177268609035216&id=100002562648073&refid=17&ref=bookmarks&_ft_=top_level_post_id.1177268609035216%3Atl_objid.1177268609035216%3Athrowback_story_fbid.1177268609035216%3Athid.100002562648073%3A306061129499414%3A2%3A0%3A1485935999%3A-8966917911936468112&__tn__=%2As

**Pull request merged**
